[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start"

[variables]
NODE_ENV = "production"
PORT = "8080"